### ISSUE TITLE
Pokemon_fire_red_base_batteryless.ips

### ISSUE THREAD

**Issue by iscarelli** [acocalypso/batteryless-patches#14]
Game freezes:

SAVING...
DON'T TURN OFF THE POWER.

Retroarch 1.15.0 
Onionos

Thanks.

**Comment by acocalypso** [comment]
Closed, unrelated issue to the repository.
For further information about the patches please check the [README](https://raw.githubusercontent.com/acocalypso/batteryless-patches/main/README.md)
