### ISSUE TITLE
Mother 1+2 Batteryless Patch

### ISSUE THREAD

**Issue by Liriel-666** [acocalypso/batteryless-patches#6]
There is a Problem that the batteryless only works with Mother 1.
But Mother 2 with this https://github.com/jeffman/Mother2GbaTranslation newer English Patch crash  after the Earthbound logo.

the patch maker says: The patch has moved some things around in order to make space for the code/new things.

With that the batteryless only work with mother 1

**Comment by acocalypso** [comment]
this patch only works on the mother 1 & mother 2 in one rom that was sold on some chinese site.
The cartridge looks like this
![image](https://user-images.githubusercontent.com/2846629/151609590-ef3b8e86-de6f-4979-86d4-307f3d975f60.png)

**Comment by Liriel-666** [comment]
I knew that.
But that's really old Translation that they have.
With newer Translation patches.
But the new Englisch Translation use space where the battery less saves and that crash the game.
A new  Patch it needed with correct space to save the game

**Comment by acocalypso** [comment]
I dont have any for a newer translation sorry.
