### ISSUE TITLE
make patch for this version of mother1+2?

### ISSUE THREAD

**Issue by manwichman44** [acocalypso/batteryless-patches#8]
Im trying to reflash abootleg cart that only uses batteryless saving. you have a patch for mother1+2, but its not completely translated. i have a rom that is and was wondering if you could make a patch for it. if this is the wrong place to request this, let me know. Thank you!

Edited

**Comment by acocalypso** [comment]
Please share any Roms.
I removed it from your post.

The batteryless latch was ripped from an bootleg. You can try to patch your version with the latch available.
